version: '3'

services:

  proxy:
    image: 'proxy.py'
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: proxy
    hostname: 'proxy'
    networks:
      - us-east-2
    volumes:
      - ./proxy.py/proxy:/code/proxy
    ports:
      - "8899:8899"
    tty: true
    command: [
      "/usr/bin/python3", "-m", "proxy", "--hostname", "0.0.0.0", "--port", "8899",
      "--plugin", "proxy.plugin.ReplyLogApiPlugin", "--rest-api-url", "http://192.168.0.109:8000"]
    depends_on:
      - kafka

  kafkaproxy:
    image: 'kafkaproxy'
    build: .
    container_name: kafkaproxy
    hostname: 'kafkaproxy'
    networks:
      - us-east-2
    volumes:
      - ./kafka-proxy/:/code/kafkaproxy
    ports:
      - "8000:8000"
    tty: true
    command: ["/usr/bin/python3", "-m", "kafkaproxy"]
    depends_on:
      - kafka
  
  zookeeper:
    image: "docker.io/bitnami/zookeeper:3"
    hostname: 'zookeeper'
    networks:
      - us-east-2
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "docker.io/bitnami/kafka:2-debian-10"
    hostname: 'kafka'
    networks:
      - us-east-2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

networks:
  us-east-2:
    driver: bridge
